name: Docker Scout

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  scout:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      security-events: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker image for scanning
      uses: docker/build-push-action@v5
      with:
        context: .
        load: true
        tags: ${{ env.IMAGE_NAME }}:scout-scan
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Docker Scout CVEs
      uses: docker/scout-action@v1
      with:
        command: cves
        image: ${{ env.IMAGE_NAME }}:scout-scan
        only-severities: critical,high,medium
        exit-code: false
        write-comment: true
        github-token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Docker Scout Compare
      if: github.event_name == 'pull_request'
      uses: docker/scout-action@v1
      with:
        command: compare
        image: ${{ env.IMAGE_NAME }}:scout-scan
        to: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:main
        exit-code: false
        write-comment: true
        github-token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Docker Scout Recommendations
      uses: docker/scout-action@v1
      with:
        command: recommendations
        image: ${{ env.IMAGE_NAME }}:scout-scan
        exit-code: false
        write-comment: true
        github-token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Upload Scout results to GitHub Security
      if: github.event_name != 'pull_request'
      uses: docker/scout-action@v1
      with:
        command: sbom
        image: ${{ env.IMAGE_NAME }}:scout-scan
        format: spdx-json
        output: scout-sbom.json
    
    - name: Upload SBOM as artifact
      if: github.event_name != 'pull_request'
      uses: actions/upload-artifact@v4
      with:
        name: scout-sbom
        path: scout-sbom.json
        retention-days: 30